/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FormRouteImport } from './routes/form'
import { Route as NeedRouteImport } from './routes/need'
import { Route as StarsRouteImport } from './routes/stars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedRoute = NeedRouteImport.update({
  id: '/need',
  path: '/need',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/form': typeof FormRoute
  '/need': typeof NeedRoute
  '/stars': typeof StarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/form': typeof FormRoute
  '/need': typeof NeedRoute
  '/stars': typeof StarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/contact': typeof ContactRoute
  '/form': typeof FormRoute
  '/need': typeof NeedRoute
  '/stars': typeof StarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparison' | '/contact' | '/form' | '/need' | '/stars'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparison' | '/contact' | '/form' | '/need' | '/stars'
  id:
    '__root__' | '/' | '/comparison' | '/contact' | '/form' | '/need' | '/stars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonRoute: typeof ComparisonRoute
  ContactRoute: typeof ContactRoute
  FormRoute: typeof FormRoute
  NeedRoute: typeof NeedRoute
  StarsRoute: typeof StarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need': {
      id: '/need'
      path: '/need'
      fullPath: '/need'
      preLoaderRoute: typeof NeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonRoute: ComparisonRoute,
  ContactRoute: ContactRoute,
  FormRoute: FormRoute,
  NeedRoute: NeedRoute,
  StarsRoute: StarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
